### PR TITLE
Fix repeated popup-card issue

### PR DESCRIPTION
**Pull request by iantrich**
Fixes https://github.com/thomasloven/lovelace-popup-card/issues/17

### CODE REVIEW

**Comment by kalkih** [comment]
Thanks @iantrich 
Do we really need all of the additional options in the event to solve this issue?

**Comment by iantrich** [comment]
I just took from your mini-graph-card, that worked and I called it good. It's probably just the stopPropagation() piece

**Comment by kalkih** [comment]
Alright, I guess we potentially could have use for it in the future.
Thanks again @iantrich !

**Comment by iantrich** [comment]
🤷‍♂  😄

**Pull request merged**
