### PR TITLE
🛠️ use local lit

### PR DESCRIPTION
**Pull request by iantrich**
fixes https://github.com/kalkih/mini-media-player/issues/57

### CODE REVIEW

**Comment by TheZoker** [comment]
Can confirm, that this fixes my issue!

**Comment by kalkih** [comment]
Cool!
This would certainly reduce the size of the card, however it would make it incompatible for people running versions of HA prior to 0.80.0 (where Lit was introduced).

**Comment by iantrich** [comment]
Very true. Could include an additional ‘or’

**Comment by ZinkNotTheMetal** [comment]
I changed this in the top line of my file and didn't have any luck, still the same issue even after a restart of HomeAssistant

**Comment by iantrich** [comment]
@ZinkNotTheMetal doesn't require a restart, you need to clear your browser cache, however

**Comment by ZinkNotTheMetal** [comment]
@iantrich thank you sir!

**Comment by kalkih** [comment]
> Very true. Could include an additional ‘or’
Yes, but the build process would then import LitElement anyway.

If it wasn't for the lost backwards compatibility I would merge this now.
But then again, people running Lovelace UI and Custom cards are probably keeping their HA fairly up to date, or what do you think?

**Comment by TheZoker** [comment]
Yea I guess these people have a update to date HA. 0.80 is also 5 version behind, so for me this step would be ok

**Comment by iantrich** [comment]
@kalkih I think a note saying that future releases are only supported by 0.80+ is fair.

**Comment by kalkih** [comment]
Thanks for your feedback.
I'll merge this at a later stage, I want to release version 1.0.0 first, so that people unwilling to update their HA at least get that version.

**Comment by kalkih** [comment]
Interesting, that could indeed be an issue and cause to cards break, especially with lit and lit-element still being young and developed quite extensively.

For now, my build process solves the issues related to externally loaded dependencies by bundling them in, the drawback being the additional size of the card.

I'm going to remove the ability to use the source directly in the next release, since people still seem to do it, and it's causing unnecessary confusion and issues.

**Comment by iantrich** [comment]
I like the bundling idea and might see about adding to mine and suggesting it to others

**Pull request closed without merging**
