### PR TITLE
WIP - individual volume adjustments in speaker group management

### PR DESCRIPTION
**Pull request by kalkih**
Add ability to control volume for individual members/speakers in speaker group management.
Also includes small refactoring of media player model.

Resolves: #404

### CODE REVIEW

**Comment by RomRider** [comment]
Just a comment on this regarding the use case of alternative entity to control groups:
For volume control in the group list, for this use case, mmp would also require to access the real entity which has volume control on top of the one which handles the grouping in the list if that makes sense (basically, it's the opposite logic of the other PR)

**Comment by kalkih** [comment]
Yes, correct, planned on solving it similarily to how you did with the `group_mgmt_entity`  by creating a `MediaPlayerObjects` for each entity in the speaker group config and also watch for state changes for those in hass to amke sure the card is up to date with the data.

https://github.com/kalkih/mini-media-player/blob/1850b351d05cf413a6931efbd90b9496383ed25e/src/main.js#L95-L107

**Comment by RomRider** [comment]
> creating a `MediaPlayerObjects` for each entity in the speaker group config and also watch for state changes for those in hass to amke sure the card is up to date with the data.

Would that be enough to handle the second player in the above example? Since the second player does only know about the sonos entity in my example, but not about the one which controls the volume. That is why I added a `main_entity` param in the example.

**Comment by kalkih** [comment]
Oh, I understand the issue now, yes that would indeed be a problem.
Will have to think about that one...

I currently do not have access to a Home Assistant setup, I want to make the development process easier and not require a running HA setup, but it's a bit tricky when the card is depending on components from exposed by Home Assistant.
[branch/add-test-environment](https://github.com/kalkih/mini-media-player/add-test-environment)

**Comment by RomRider** [comment]
Your branch is not available on GH.
For what it's worth, I've used this as my devcontainer to do the other PR:
```json
// See https://aka.ms/vscode-remote/devcontainer.json for format details.
{
  "name": "mini-media-player Development",
  "image": "ludeeus/container:monster",
  "appPort": ["5000:5000", "9123:8123"],
  "postCreateCommand": "npm install",
  "runArgs": [
    "-v",
    "${env:HOME}${env:USERPROFILE}/.ssh:/tmp/.ssh", // This is added so you can push from inside the container
  ],
  "extensions": [
    "github.vscode-pull-request-github",
    "eamodio.gitlens",
    "dbaeumer.vscode-eslint",
    "bierner.lit-html",
    "runem.lit-plugin",
    "auchenberg.vscode-browser-preview",
    "davidanson.vscode-markdownlint",
    "redhat.vscode-yaml",
    "msjsdiag.debugger-for-chrome",
    "yzhang.markdown-all-in-one"
  ],
  "settings": {
    "files.eol": "\n",
    "editor.tabSize": 2,
    "terminal.integrated.shell.linux": "/bin/bash",
    "editor.formatOnPaste": false,
    "editor.formatOnSave": true,
    "editor.formatOnType": true,
    "files.trimTrailingWhitespace": true,
    "markdown.extension.toc.githubCompatibility": true,
    "files.watcherExclude": {
      "**/.git/objects/**": true,
      "**/.git/subtree-cache/**": true,
      "**/node_modules/**": true,
      "**/.hg/store/**": true,
      "**/.rpt2_cache/**": true
    }
  }
}
```

If you're not familiar with the devcontainer from ludeeus, it includes a working home-assistant that you can start with `container start` from a shell inside the dev container.
You can also check the button-card which I maintain (https://github.com/custom-cards/button-card), where I'm using a dev container also for vscode.

**Comment by kalkih** [comment]
I butchered the link apparently... fixed now.

Interesting, will have to look into that, thank you.
Is there a way to mock entities as well that you're aware of?

**Comment by RomRider** [comment]
Unfortunately not :(
You can use the `demo` environment (just add `demo:` to your configuration.yaml) which provides a dummy media_player but it will not provide all the features you expect.

**Pull request closed without merging**
