### PR TITLE
Switch checkbox to toggle in speaker management

### PR DESCRIPTION
**Pull request by kalkih**

### CODE REVIEW

**Comment by kalkih** [comment]
@RomRider Do you have time to try this?
Checkboxes looked a bit weird without the proper styling so I switched to toggles, what do you think?

**Comment by RomRider** [comment]
I'll check that tomorrow 👍

**Comment by RomRider** [comment]
Works as expected 👍

I'd maybe adjust the font weight though, currently it's `500` which is more than the default `var(--mmp-name-font-weight)` at `400`. Maybe the master should be kept at `500` and disabled items should have another color (not only the switch but the text also: opacity of the disabled switch is `0.38`, I've set `0.5` for the text in the screenshot)

* current:

  image

* with some manual modifications in chrome dev tools:

  image

**Comment by kalkih** [comment]
Thanks for the feedback, addressed all points except the opacity of disabled switches since there is no CSS custom property to change that.

**Comment by RomRider** [comment]
Disabled switches have a `0.38` by default, so all good :)

**Comment by kalkih** [comment]
Yes, a bit too low when there's background artwork imo, but it is what it is 🙂

**Pull request merged**
